
Vagrant.configure("2") do |config|


#my vbox name
#we can see that with "vagrant box list"
  config.vm.box = "bento/ubuntu-22.04"

#choose a ip
   config.vm.network "private_network", ip: "192.168.56.50"


#choose a hostname
  config.vm.hostname = "vm_test"


#setting hardware
  config.vm.provider "virtualbox" do |my_vm|
#choose a name in list vagrant
    my_vm.name = "my_vm"
#choose memory for this machine
    my_vm.memory = "1024"
#choose cpu core
    my_vm.cpus = 2
  end


#if we have some script before load machine like "sudo apt update"
 #config.vm.provision :shell, path: "script.sh"
end
